title: "Kush's Blogs"

social_links:
  - name: GitHub
    url: "https://github.com/Kush-Singh-26"
  - name: Profile
    url: "https://kush-singh-26.github.io/"
  - name: Blogs Repo
    url: "https://github.com/Kush-Singh-26/blogs_obsolete"

baseurl: "/blogs_obsolete"           # Set to the subdirectory if applicable
url: "https://kush-singh-26.github.io"  # Root URL of your GitHub Pages

github_username: Kush-Singh-26

# Theme settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

include:
  - "favicon.png"
  - "_tags"

collections:
  tags:
    output: true
    permalink: /tags/:name/

minima:
  skin: dark

header_pages:

markdown: kramdown
highlighter: rouge
